import type { FlowId, ProductionMitigation } from "./types";

/** Mitigações candidatas a produção (derivadas do lab resilience + auditoria). */
export const PRODUCTION_MITIGATIONS: ProductionMitigation[] = [
  {
    id: "M1",
    name: "AUTH_SECRET só em env Vercel + rotação JWT",
    priority: "P0",
    touchpoints: ["vercel.json", "src/lib/auth/*", "middleware"],
    affectedFlows: ["auth-sessao", "hb-credit-mercado", "conta-coop", "cobranca-asaas"],
    riskIfRushed: "Todos logados deslogados; HB Créditos/API 401 até redeploy coordenado.",
    prerequisiteIds: [],
    safeguards: ["Deploy com secret novo + grace period 1h dual-secret", "Aviso manutenção 15 min"],
  },
  {
    id: "M2",
    name: "Corrigir merge mensalidade cooperado vê status paga",
    priority: "P0",
    touchpoints: [
      "cooperativaSyncCloudService.ts (mergeOperacionalIntoData)",
      "mensalidadeService.ts",
    ],
    affectedFlows: ["mensalidade", "sync-offline"],
    riskIfRushed: "Regressão em merge de outras entidades operacionais.",
    prerequisiteIds: [],
    safeguards: ["npm run test:sync-flows 100% verde antes de merge", "Teste manual cooperado+resp"],
  },
  {
    id: "M3",
    name: "Bloqueio push incoerente (ficha duplicada)",
    priority: "P1",
    touchpoints: ["cooperativaSyncCloudService.ts pushOperacionalToCloud", "fichaSyncGuard.ts"],
    affectedFlows: ["ficha-pagamento", "notas-conferencia", "sync-offline"],
    riskIfRushed: "Responsável não consegue salvar; dados legítimos bloqueados.",
    prerequisiteIds: ["M2"],
    safeguards: ["Modo warn-only 1 semana (log + banner)", "Depois block só severity=block"],
  },
  {
    id: "M4",
    name: "Sync por slices (manifest remoto)",
    priority: "P1",
    touchpoints: [
      "cooperativaSyncStorage.ts",
      "cooperativaSyncCloudService.ts",
      "CooperativaSyncProvider.tsx",
      "api/cooperativa-sync",
    ],
    affectedFlows: ["sync-offline", "votacao-assinatura", "ficha-pagamento", "mensalidade", "livro-fechamento"],
    riskIfRushed: "Dados parciais: cooperado vê ficha nova mas votação antiga.",
    prerequisiteIds: ["M2", "M3"],
    safeguards: ["Feature flag HB_SYNC_SLICES=false default", "Pilot 1 CNPJ", "Fallback monolito"],
  },
  {
    id: "M5",
    name: "Gate FSM assinatura no push cooperado",
    priority: "P1",
    touchpoints: ["cooperadoAssinaturaService.ts", "cooperadoCloudService.ts"],
    affectedFlows: ["votacao-assinatura", "cooperado-cadastro"],
    riskIfRushed: "Cooperado legado com foto bloqueado.",
    prerequisiteIds: [],
    safeguards: ["Exempt status implícito confirmada (legado)", "Mensagem clara no app"],
  },
  {
    id: "M6",
    name: "Preditor capacidade + alerta 80%",
    priority: "P2",
    touchpoints: ["platformCapacityService.ts", "AdminSistemaPanel.tsx", "dashboard responsável"],
    affectedFlows: ["admin-plataforma", "sync-offline"],
    riskIfRushed: "Nenhum fluxo quebrado — só alertas.",
    prerequisiteIds: [],
    safeguards: ["Somente leitura/alerta", "Sem bloqueio automático inicialmente"],
  },
  {
    id: "M7",
    name: "Arquivamento operacional meses antigos",
    priority: "P2",
    touchpoints: ["cooperativaSyncStorage.ts", "novo job archive"],
    affectedFlows: ["livro-fechamento", "ficha-pagamento", "sync-offline"],
    riskIfRushed: "Relatórios históricos incompletos; contador perde mês arquivado.",
    prerequisiteIds: ["M6"],
    safeguards: ["Arquivar só >12 meses", "Download antes de arquivar", "Opt-in responsável"],
  },
  {
    id: "M8",
    name: "Painel dedupe cooperados homônimos",
    priority: "P2",
    touchpoints: ["cooperados/page.tsx", "novo serviço mergeCooperado"],
    affectedFlows: ["cooperado-cadastro", "ficha-pagamento", "hb-credit-mercado"],
    riskIfRushed: "Merge errado une fichas de pessoas diferentes.",
    prerequisiteIds: [],
    safeguards: ["Só admin/responsável confirma", "Preview diff antes de merge", "Nunca auto-merge"],
  },
];

export const FLOW_LABELS: Record<FlowId, string> = {
  "notas-conferencia": "Notas → conferência → ficha",
  "ficha-pagamento": "Ficha corrida · pagamentos · recibos",
  mensalidade: "Mensalidade cooperado ↔ responsável",
  "votacao-assinatura": "Votação · assinatura cadastro",
  "hb-credit-mercado": "HB Créditos · mercado parceiro",
  "conta-coop": "Conta Coop · limites · repasse",
  "cobranca-asaas": "Cobrança HB · Asaas PIX",
  "sync-offline": "Sync offline · push/pull nuvem",
  "auth-sessao": "Login · JWT · sessão",
  "admin-plataforma": "Admin HB · multi-cooperativa",
  "livro-fechamento": "Livro caixa · fechamento · contador",
  "cooperado-cadastro": "Cadastro cooperado · Meu cadastro",
};
