import type { ImpactScenario } from "./types";

/**
 * Catálogo de cenários previsíveis e imprevisíveis —
 * avalia impacto SE cada mitigação for para produção.
 */
export function buildScenarioCatalog(): ImpactScenario[] {
  return [
    // --- M1 AUTH ---
    {
      id: "S01",
      kind: "previsivel",
      flow: "auth-sessao",
      title: "Deploy rotação AUTH_SECRET desloga todos",
      trigger: "M1 em produção sem dual-secret",
      mitigationsInvolved: ["M1"],
      naiveOk: false,
      naiveNote: "Sessões JWT invalidadas instantaneamente.",
      refinedOk: true,
      refinedNote: "Dual-secret 1h + redeploy; usuários relogam uma vez.",
      userVisibleBreak: "Todos precisam entrar de novo no app.",
    },
    {
      id: "S02",
      kind: "imprevisivel",
      flow: "hb-credit-mercado",
      title: "Mercado parceiro 401 após rotação secret",
      trigger: "M1 deploy parcial (Vercel A ok, cron B antigo)",
      mitigationsInvolved: ["M1"],
      naiveOk: false,
      naiveNote: "Edge functions com secret velho rejeitam token.",
      refinedOk: true,
      refinedNote: "Deploy atômico + verificar CRON_SECRET alinhado.",
    },
    // --- M2 MENSALIDADE ---
    {
      id: "S03",
      kind: "previsivel",
      flow: "mensalidade",
      title: "Cooperado não vê mensalidade paga após sync",
      trigger: "Bug atual mergeOperacionalIntoData (test:sync-flows FAIL)",
      mitigationsInvolved: ["M2"],
      naiveOk: false,
      naiveNote: "Regressão conhecida — 1/11 testes sync falha hoje.",
      refinedOk: true,
      refinedNote: "Fix merge + test:sync-flows verde antes de qualquer outro sync change.",
      userVisibleBreak: "Cooperado acha que mensalidade não foi confirmada.",
    },
    {
      id: "S04",
      kind: "imprevisivel",
      flow: "mensalidade",
      title: "Dois dispositivos cooperado: status diverge",
      trigger: "M2 fix incompleto no merge by updatedAt",
      mitigationsInvolved: ["M2"],
      naiveOk: false,
      naiveNote: "Celular A paga, B ainda pendente até pull.",
      refinedOk: true,
      refinedNote: "Merge by newer updatedAt + pull ao abrir app.",
    },
    // --- M3 COHERENCE BLOCK ---
    {
      id: "S05",
      kind: "previsivel",
      flow: "ficha-pagamento",
      title: "Push bloqueado por ficha duplicada legítima pós-sync",
      trigger: "M3 block ativo sem warn-only",
      mitigationsInvolved: ["M3"],
      naiveOk: false,
      naiveNote: "Duplicata fantasma de sync antigo trava responsável.",
      refinedOk: true,
      refinedNote: "Warn-only + ferramenta dedupe ficha antes de block.",
      userVisibleBreak: "Responsável vê 'Não foi possível sincronizar'.",
    },
    {
      id: "S06",
      kind: "imprevisivel",
      flow: "notas-conferencia",
      title: "Conferência nota cria ficha; push bloqueia antes de nuvem ver",
      trigger: "M3 + race conferência rápida",
      mitigationsInvolved: ["M3"],
      naiveOk: false,
      naiveNote: "Falso positivo duplicata na mesma sessão.",
      refinedOk: true,
      refinedNote: "Dedupe local antes de validate; block só id+mes+notaId iguais.",
    },
    {
      id: "S07",
      kind: "previsivel",
      flow: "sync-offline",
      title: "Responsável offline acumula push; block ao voltar online",
      trigger: "M3 sem fila de correção",
      mitigationsInvolved: ["M3"],
      naiveOk: false,
      naiveNote: "Dados locais inconsistentes acumulados offline.",
      refinedOk: true,
      refinedNote: "Banner com lista de conflitos + botão reparar.",
    },
    // --- M4 SLICES ---
    {
      id: "S08",
      kind: "previsivel",
      flow: "votacao-assinatura",
      title: "Votação desatualizada enquanto ficha já syncou",
      trigger: "M4 slices parciais sem ordem P0",
      mitigationsInvolved: ["M4"],
      naiveOk: false,
      naiveNote: "Slice ficha novo, votacao slice stale.",
      refinedOk: true,
      refinedNote: "Abrir votação força pull P0 slices; flag off = monolito.",
      userVisibleBreak: "Cooperado vota em pauta que já fechou na nuvem.",
    },
    {
      id: "S09",
      kind: "imprevisivel",
      flow: "sync-offline",
      title: "Rollback flag slices; manifest órfão na nuvem",
      trigger: "M4 desligado após pilot; clientes com manifest",
      mitigationsInvolved: ["M4"],
      naiveOk: false,
      naiveNote: "Cliente espera slices; servidor monolito.",
      refinedOk: true,
      refinedNote: "Fallback: manifest ausente → pull monolito completo.",
    },
    {
      id: "S10",
      kind: "previsivel",
      flow: "ficha-pagamento",
      title: "Pagamento registrado; slice financeiro atrasado",
      trigger: "M4 gap P1 no financeiro",
      mitigationsInvolved: ["M4"],
      naiveOk: false,
      naiveNote: "Cooperado não vê pagamento 25–120s.",
      refinedOk: true,
      refinedNote: "Pagamento push inclui slice financeiro dirty imediato.",
    },
    {
      id: "S11",
      kind: "imprevisivel",
      flow: "livro-fechamento",
      title: "Contador abre relatório; slice ficha incompleto",
      trigger: "M4 pull seletivo errado no perfil contador",
      mitigationsInvolved: ["M4"],
      naiveOk: false,
      naiveNote: "Relatório R3 com totais parciais.",
      refinedOk: true,
      refinedNote: "Perfil contador sempre pull ficha+financeiro+livro.",
    },
    // --- M5 ASSINATURA FSM ---
    {
      id: "S12",
      kind: "previsivel",
      flow: "votacao-assinatura",
      title: "Legado com foto bloqueado pelo gate FSM",
      trigger: "M5 sem exempt legado",
      mitigationsInvolved: ["M5"],
      naiveOk: false,
      naiveNote: "Ailton/Jeferson/Júlio perdem assinatura em docs.",
      refinedOk: true,
      refinedNote: "Legado (foto sem status) = confirmada; gate só em transição.",
      userVisibleBreak: "Cooperado não consegue assinar recibo.",
    },
    {
      id: "S13",
      kind: "imprevisivel",
      flow: "cooperado-cadastro",
      title: "Push assinatura em_analise sem foto (race upload)",
      trigger: "M5 + rede lenta; dataUrl ainda não no payload",
      mitigationsInvolved: ["M5"],
      naiveOk: false,
      naiveNote: "Falso block cooperado honesto.",
      refinedOk: true,
      refinedNote: "Gate só no servidor após blob completo; retry client.",
    },
    // --- M6 CAPACITY ---
    {
      id: "S14",
      kind: "previsivel",
      flow: "admin-plataforma",
      title: "Alerta 80% operacional sem ação",
      trigger: "M6 só alerta",
      mitigationsInvolved: ["M6"],
      naiveOk: true,
      naiveNote: "Não quebra fluxo — informacional.",
      refinedOk: true,
      refinedNote: "Responsável arquiva manualmente ou ignora até P2.",
    },
    {
      id: "S15",
      kind: "imprevisivel",
      flow: "sync-offline",
      title: "Push 5 MB rejeitado Supabase mid-operação",
      trigger: "Sem M6/M7; histórico 18 meses",
      mitigationsInvolved: ["M6", "M7"],
      naiveOk: false,
      naiveNote: "Sync falha silencioso; dados só local.",
      refinedOk: true,
      refinedNote: "M6 alerta + M7 arquivamento antes de 95%.",
      userVisibleBreak: "Cooperados param de receber atualizações.",
    },
    // --- M7 ARCHIVE ---
    {
      id: "S16",
      kind: "previsivel",
      flow: "livro-fechamento",
      title: "Contador não acha mês arquivado",
      trigger: "M7 arquivar sem export",
      mitigationsInvolved: ["M7"],
      naiveOk: false,
      naiveNote: "Dossiê ZIP incompleto.",
      refinedOk: true,
      refinedNote: "Arquivar só após snapshot fechamento + download oferecido.",
    },
    // --- M8 DEDUPE ---
    {
      id: "S17",
      kind: "previsivel",
      flow: "cooperado-cadastro",
      title: "Merge homônimos une pessoas diferentes",
      trigger: "M8 auto-merge ou confirmação apressada",
      mitigationsInvolved: ["M8"],
      naiveOk: false,
      naiveNote: "Ficha e HB Créditos de pessoas distintas colidem.",
      refinedOk: true,
      refinedNote: "Preview diff obrigatório; CPF diferente = block merge.",
      userVisibleBreak: "Valores errados na ficha do cooperado.",
    },
    {
      id: "S18",
      kind: "imprevisivel",
      flow: "hb-credit-mercado",
      title: "Conta Coop limite no ID errado pós-merge",
      trigger: "M8 merge sem migrar hb_credit refs",
      mitigationsInvolved: ["M8"],
      naiveOk: false,
      naiveNote: "Orlando compra no ID fantasma.",
      refinedOk: true,
      refinedNote: "Merge migra cooperadoId em ficha, notas, hb_credit.",
    },
    // --- FLUXOS OPERACIONAIS ATUAIS (sem mitigação nova) ---
    {
      id: "S19",
      kind: "previsivel",
      flow: "notas-conferencia",
      title: "21+ cooperados enviam notas simultâneo",
      trigger: "Produção atual CoopeagriPla",
      mitigationsInvolved: [],
      naiveOk: true,
      naiveNote: "Validado em produção real pelo usuário.",
      refinedOk: true,
      refinedNote: "Manter; M3/M4 não bloqueiam se ordem correta.",
    },
    {
      id: "S20",
      kind: "previsivel",
      flow: "hb-credit-mercado",
      title: "Mercado Orlando fluxo compra+nota",
      trigger: "Produção atual",
      mitigationsInvolved: [],
      naiveOk: true,
      naiveNote: "Homologado pelo usuário.",
      refinedOk: true,
      refinedNote: "M1 rotação JWT exige mercado relogar.",
    },
    {
      id: "S21",
      kind: "imprevisivel",
      flow: "sync-offline",
      title: "Dois responsáveis editam operacional simultâneo",
      trigger: "Last-write-wins monolito (atual)",
      mitigationsInvolved: ["M4"],
      naiveOk: false,
      naiveNote: "Último push ganha — perda silenciosa.",
      refinedOk: false,
      refinedNote: "M4 slices reduz blast radius; 3-way merge futuro. Risco residual aceito.",
    },
    {
      id: "S22",
      kind: "imprevisivel",
      flow: "ficha-pagamento",
      title: "Cooperado assina recibo; push falha rede",
      trigger: "Produção atual",
      mitigationsInvolved: [],
      naiveOk: true,
      naiveNote: "Recibo local ok; retry sync manual.",
      refinedOk: true,
      refinedNote: "M3 não bloqueia se dados coerentes.",
    },
    {
      id: "S23",
      kind: "previsivel",
      flow: "cobranca-asaas",
      title: "Asaas PF ainda em análise",
      trigger: "Externo Asaas",
      mitigationsInvolved: [],
      naiveOk: true,
      naiveNote: "PIX manual/cobrança aviso; core coop ok.",
      refinedOk: true,
      refinedNote: "Independente das mitigações lab.",
    },
    {
      id: "S24",
      kind: "imprevisivel",
      flow: "conta-coop",
      title: "Estorno mercado + sync operacional overlap",
      trigger: "HB Créditos + push operacional",
      mitigationsInvolved: ["M3", "M4"],
      naiveOk: true,
      naiveNote: "Conta Coop server-side isolado.",
      refinedOk: true,
      refinedNote: "Mitigações sync não alteram API credit.",
    },
    {
      id: "S25",
      kind: "previsivel",
      flow: "votacao-assinatura",
      title: "Assinatura devolvida → reenvio → confirmada",
      trigger: "Fluxo assinatura recente",
      mitigationsInvolved: ["M5"],
      naiveOk: true,
      naiveNote: "Implementado e em produção.",
      refinedOk: true,
      refinedNote: "M5 reforça; não quebra se legado exempt.",
    },
    {
      id: "S26",
      kind: "imprevisivel",
      flow: "notas-conferencia",
      title: "Foto entrega 50 MB bucket timeout",
      trigger: "Rede rural lenta",
      mitigationsInvolved: [],
      naiveOk: true,
      naiveNote: "Pipeline compressão existente.",
      refinedOk: true,
      refinedNote: "Fora escopo mitigações lab.",
    },
    {
      id: "S27",
      kind: "previsivel",
      flow: "cooperado-cadastro",
      title: "27 JSONs com 3 Ana Maria duplicadas",
      trigger: "Dados CoopeagriPla atuais",
      mitigationsInvolved: ["M8"],
      naiveOk: false,
      naiveNote: "Cobrança/contagem inflada; confusão responsável.",
      refinedOk: true,
      refinedNote: "M8 dedupe manual; não auto.",
    },
    {
      id: "S28",
      kind: "imprevisivel",
      flow: "auth-sessao",
      title: "Token expira mid-votação",
      trigger: "Sessão longa + JWT TTL",
      mitigationsInvolved: ["M1"],
      naiveOk: true,
      naiveNote: "Comportamento atual.",
      refinedOk: true,
      refinedNote: "M1 não altera TTL se só rotacionar secret.",
    },
    {
      id: "S29",
      kind: "previsivel",
      flow: "livro-fechamento",
      title: "Fechamento mensal + sync push authoritative",
      trigger: "Responsável fecha mês",
      mitigationsInvolved: ["M3", "M4"],
      naiveOk: true,
      naiveNote: "pushOperacional authoritative hoje.",
      refinedOk: true,
      refinedNote: "M3 warn-only não bloqueia fechamento limpo.",
    },
    {
      id: "S30",
      kind: "imprevisivel",
      flow: "admin-plataforma",
      title: "Admin HB carrega 20 coop no mesmo browser",
      trigger: "Escala SaaS futura",
      mitigationsInvolved: ["M6"],
      naiveOk: false,
      naiveNote: "localStorage ~5 MB estoura.",
      refinedOk: true,
      refinedNote: "Admin nuvem-only views; não persistir 20 coop local.",
    },
    // --- COMBINAÇÕES (imprevisível) ---
    {
      id: "S31",
      kind: "imprevisivel",
      flow: "sync-offline",
      title: "M1+M4+M3 no mesmo deploy",
      trigger: "Big bang release",
      mitigationsInvolved: ["M1", "M3", "M4"],
      naiveOk: false,
      naiveNote: "Impossível isolar regressão.",
      refinedOk: true,
      refinedNote: "1 PR por mitigação; ordem M2→M1→M3 warn→M5→M4 flag.",
    },
    {
      id: "S32",
      kind: "imprevisivel",
      flow: "mensalidade",
      title: "M2 fix + M4 slices alteram merge mensalidades",
      trigger: "M4 refatora merge path",
      mitigationsInvolved: ["M2", "M4"],
      naiveOk: false,
      naiveNote: "Regressão mensalidade de novo.",
      refinedOk: true,
      refinedNote: "M2 merged + test:sync-flows gate antes M4.",
    },
    {
      id: "S33",
      kind: "previsivel",
      flow: "ficha-pagamento",
      title: "Valor receber cooperado desalinhado pós-sync",
      trigger: "fichaSyncGuard + merge",
      mitigationsInvolved: ["M2", "M4"],
      naiveOk: true,
      naiveNote: "CooperadoFinanceiroGate repara hoje.",
      refinedOk: true,
      refinedNote: "Manter gate; testar após M4 pilot.",
    },
    {
      id: "S34",
      kind: "imprevisivel",
      flow: "notas-conferencia",
      title: "Reset operacional acidental com cooperados ativos",
      trigger: "Admin reset + M3 block push restore",
      mitigationsInvolved: ["M3"],
      naiveOk: false,
      naiveNote: "Restore backup + push bloqueado por duplicatas pós-restore.",
      refinedOk: true,
      refinedNote: "Pós-restore: bypass block 24h + dedupe script.",
    },
    {
      id: "S35",
      kind: "previsivel",
      flow: "hb-credit-mercado",
      title: "HB_CREDIT_ENABLED + AUTH rotacionado",
      trigger: "M1 + credit API",
      mitigationsInvolved: ["M1"],
      naiveOk: true,
      naiveNote: "Mesmo secret family.",
      refinedOk: true,
      refinedNote: "Rotacionar AUTH_SECRET e CRON_SECRET juntos.",
    },
  ];
}
